const tstDive = new TasteDive();
const wiki = new WikiMedia();
const cocktails = new CockTail();
// ALL DOCUMENT GET SELECTORS----------------------------------------------------------------------

const movieDetail = document.getElementById("card-movie-desc");

const movieImg = document.getElementById("movie-image");

const drinkDetail = document.getElementById("card-drink-desc");

const drinkImg = document.getElementById("drink-image");

const movies = document.getElementById("movie-api-data-list");

const searchMovies = document.getElementById("search-movies");

const movieList = document.querySelector(".movie-api-data-list");

const searchDropdown = document.getElementById("search-dropdown");
const instuct = document.getElementById("instruction");
const moviesContainer = document.getElementById("movies-container");
const drinksContainer = document.getElementById("drinks-container");
const movieoptions = [
    "300",
    "1408",
    "1917",
    "2012",
    "10 Things I Hate About You",
    "101 Dalmatians",
    "101 Dalmatians II: Patch's London Adventure",
    "102 Dalmatians",
    "12 Angry Men",
    "12 Strong",
    "12 Years a Slave",
    "127 Hours",
    "13 Hours: The Secret Soldiers of Benghazi",
    "16 Blocks",
    "16 Wishes",
    "17 Again",
    "18 Year Old Virgin",
    "2 Gisht Mjaltë",
    "2 Guns",
    "2001: A Space Odyssey",
    "21 Bridges",
    "21 Jump Street",
    "22 Jump Street",
    "23-F: la película",
    "24 Hours to Live",
    "27 Dresses",
    "28 Days Later",
    "28 Weeks Later",
    "3 Days to Kill",
    "3 Idiots",
    "3 Ninjas",
    "3:10 to Yuma",
    "30 Days of Night",
    "30 Days of Night: Dark Days",
    "300: Rise of an Empire",
    "47 Meters Down",
    "47 Meters Down: Uncaged",
    "47 Ronin",
    "50 First Dates",
    "6 Days",
    "6 Underground",
    "7 Days in Entebbe",
    "8 Mile",
    "9 Songs",
    "90 Minutes in Heaven",
    "A Bad Moms Christmas",
    "A Beautiful Day in the Neighborhood",
    "A Beautiful Mind",
    "A Bug's Life",
    "A Christmas Carol",
    "A Cinderella Story",
    "A Cinderella Story: Christmas Wish",
    "A Cinderella Story: If the Shoe Fits",
    "A Clockwork Orange",
    "A Cure for Wellness",
    "A Dog's Journey",
    "A Dog's Purpose",
    "A Dog's Way Home",
    "A Fall From Grace",
    "A Family Man",
    "A Few Good Men",
    "A Fish Called Wanda",
    "A Good Day to Die Hard",
    "A Goofy Movie",
    "A Grand Day Out",
    "A Haunted House 2",
    "A Hidden Life",
    "A History of Violence",
    "A Hologram for the King",
    "A Kind of Murder",
    "A Knight's Tale",
    "A Little Chaos",
    "A Mighty Heart",
    "A Most Violent Year",
    "A Nightmare on Elm Street",
    "A Nightmare on Elm Street Part 2: Freddy's Revenge",
    "A pesar de todo",
    "A Prairie Home Companion",
    "A Prayer Before Dawn",
    "A Quiet Place",
    "A Quiet Place Part II",
    "A Rainy Day in New York",
    "A Shaun the Sheep Movie: Farmageddon",
    "A Simple Favor",
    "A Star Is Born",
    "A United Kingdom",
    "A View to a Kill",
    "A Walk Among the Tombstones",
    "A Walk to Remember",
    "A Wrinkle in Time",
    "A-X-L",
    "A.I. Artificial Intelligence",
    "Abduction",
    "Abigail",
    "Abigail Haunting",
    "Abominable",
    "About Time",
    "Accepted",
    "Ace Ventura: Pet Detective",
    "Ace Ventura: When Nature Calls",
    "Acts of Vengeance",
    "Acts of Violence",
    "Ad Astra",
    "Addams Family Values",
    "Addicted",
    "Æon Flux",
    "After",
    "After Earth",
    "After Porn Ends 2",
    "After Porn Ends 3",
    "After We Collided",
    "Aftermath",
    "Agent Cody Banks 2: Destination London",
    "Air Bud",
    "Airplane!",
    "Airport 1975",
    "Aladdin",
    "Aladdin and the King of Thieves",
    "Alexander",
    "Alibi.com",
    "Alice in Wonderland",
    "Alice Through the Looking Glass",
    "Alien",
    "Alien Resurrection",
    "Alien: Covenant",
    "Alien³",
    "Aliens",
    "Aliens vs Predator: Requiem",
    "Alita: Battle Angel",
    "All Eyez on Me",
    "All the Bright Places",
    "All the King's Men",
    "All the President's Men",
    "All the Pretty Horses",
    "Allegiant",
    "Allied",
    "Almost Famous",
    "Aloha",
    "Along Came Polly",
    "Alpha",
    "Alvin and the Chipmunks",
    "Alvin and the Chipmunks: Chipwrecked",
    "Alvin and the Chipmunks: The Road Chip",
    "Alvin and the Chipmunks: The Squeakquel",
    "Amadeus",
    "Amazing Grace",
    "American Beauty",
    "American Factory",
    "American Gangster",
    "American History X",
    "American Hustle",
    "American Made",
    "American Pastoral",
    "American Pie",
    "American Pie 2",
    "American Pie Presents: Band Camp",
    "American Pie Presents: Beta House",
    "American Pie Presents: The Book of Love",
    "American Pie Presents: The Naked Mile",
    "American Psycho",
    "American Reunion",
    "American Sniper",
    "American Ultra",
    "American Wedding",
    "Amityville: The Awakening",
    "An American Tail",
    "Anaconda",
    "Anacondas: The Hunt for the Blood Orchid",
    "Anacondas: Trail of Blood",
    "Analog Love",
    "Analyze That",
    "Analyze This",
    "Anastasia",
    "Anchorman 2: The Legend Continues",
    "And So It Goes",
    "Ang Pangarap Kong Holdap",
    "Angel Has Fallen",
    "Angels & Demons",
    "Anger Management",
    "Animal Kingdom",
    "Anita",
    "Anna",
    "Annabelle",
    "Annabelle Comes Home",
    "Annabelle: Creation",
    "Annie",
    "Annihilation",
    "Anon",
    "Another Cinderella Story",
    "Ant-Man",
    "Ant-Man and the Wasp",
    "Antrum",
    "Antz",
    "Any Given Sunday",
    "Apocalypse Now",
    "Apocalypto",
    "Apollo 11",
    "Apollo 13",
    "Appetite for Love",
    "Aquaman",
    "Arctic",
    "Argo",
    "Arjona Circo Soledad en Vivo",
    "Armageddon",
    "Army of Darkness",
    "Around the World in 80 Days",
    "Arrival",
    "Arthur 3: la guerre des deux mondes",
    "Arthur et la vengeance de Maltazard",
    "As Good as It Gets",
    "Assassin 33 A.D.",
    "Assassin's Creed",
    "Assault on Precinct 13",
    "Astérix - Le Secret de la Potion Magique",
    "Astérix & Obélix contre César",
    "Astérix & Obélix Mission Cléopâtre",
    "Astérix et Cléopâtre",
    "Astérix: Le domaine des dieux",
    "Athena",
    "Atlantis: Milo's Return",
    "Atomic Blonde",
    "Atonement",
    "Au revoir là-haut",
    "August Rush",
    "August Underground's Penance",
    "Austenland",
    "Austin Powers in Goldmember",
    "Austin Powers: International Man of Mystery",
    "Autómata",
    "Avatar",
    "Avengement",
    "Avengers: Age of Ultron",
    "Avengers: Endgame",
    "Avengers: Infinity War",
    "AVP: Alien vs. Predator",
    "Babe",
    "Babel",
    "Baby Boy",
    "Baby Driver",
    "Baby's Day Out",
    "Babylon A.D.",
    "Back to the Future",
    "Back to the Future Part II",
    "Back to the Future Part III",
    "Backdraft",
    "Backtrace",
    "Bacurau",
    "Bad Boys",
    "Bad Boys for Life",
    "Bad Boys II",
    "Bad Moms",
    "Bad Sister",
    "Bad Therapy",
    "Bad Times at the El Royale",
    "Bad Trip",
    "Bahubali: The Beginning",
    "Bait",
    "Ballerina",
    "Ballet Shoes",
    "Ballon",
    "Balto II: Wolf Quest",
    "Bambi",
    "Bambi II",
    "Banlieue 13",
    "Bao",
    "Barbie and the Diamond Castle",
    "Barbie and the Magic of Pegasus 3-D",
    "Barbie and the Three Musketeers",
    "Barbie as Rapunzel",
    "Barbie as the Island Princess",
    "Barbie as The Princess & the Pauper",
    "Barbie Fairytopia: Magic of the Rainbow",
    "Barbie Fairytopia: Mermaidia",
    "Barbie in A Mermaid Tale",
    "Barbie in Princess Power",
    "Barbie in the 12 Dancing Princesses",
    "Barbie in the Nutcracker",
    "Barbie in the Pink Shoes",
    "Barbie Mariposa",
    "Barbie of Swan Lake",
    "Barbie: A Fashion Fairytale",
    "Barbie: Fairytopia",
    "Barbie: Princess Charm School",
    "Barbie: Spy Squad",
    "Barbie: The Pearl Princess",
    "Barbie: The Princess & The Popstar",
    "Barely Lethal",
    "Barry Lyndon",
    "Basic Instinct",
    "Basic Instinct 2",
    "Batman",
    "Batman & Robin",
    "Batman Begins",
    "Batman Forever",
    "Batman Returns",
    "Batman v Superman: Dawn of Justice",
    "Batman: Bad Blood",
    "Batman: Under the Red Hood",
    "Battle for the Planet of the Apes",
    "Battle: Los Angeles",
    "Battleship",
    "Baywatch",
    "Be Cool",
    "Bean",
    "Beastie Boys Story",
    "Beautiful Boy",
    "Beauty & the Briefcase",
    "Beauty and the Beast",
    "Beauty and the Beast: The Enchanted Christmas",
    "Becoming",
    "Bedazzled",
    "Bee Movie",
    "Beethoven",
    "Beetlejuice",
    "Before I Go to Sleep",
    "Before Sunrise",
    "Begin Again",
    "Behaving Badly",
    "Behind Enemy Lines",
    "Behind You",
    "Being John Malkovich",
    "Below Her Mouth",
    "Ben Is Back",
    "Ben-Hur",
    "Beneath the Planet of the Apes",
    "Beowulf & Grendel",
    "Berlin Alexanderplatz",
    "Betonrausch",
    "Beverly Hills Cop",
    "Beverly Hills Cop II",
    "Beverly Hills Cop III",
    "Beyond Before",
    "Beyond Re-Animator",
    "Beyond the Reach",
    "Big",
    "Big Fish",
    "Big Hero 6",
    "Big Momma's House",
    "Big Night!",
    "Billy Lynn's Long Halftime Walk",
    "Biohazard: Damnation",
    "Bird Box",
    "Black and Blue",
    "Black Butterfly",
    "Black Christmas",
    "Black Hawk Down",
    "Black Panther",
    "Black Snake Moan",
    "Black Swan",
    "Black Water",
    "Black Widow",
    "Blackhat",
    "BlacKkKlansman",
    "Blade",
    "Blade II",
    "Blade Runner",
    "Blade Runner 2049",
    "Blade: Trinity",
    "Blank Check",
    "Bleed for This",
    "Blended",
    "Bless the Child",
    "Blinded by the Light",
    "Blockers",
    "Blood Diamond",
    "Blood Father",
    "Bloodshot",
    "Blow",
    "Blue Lagoon: The Awakening",
    "Blue Story",
    "Blue Velvet",
    "Body of Lies",
    "Bohemian Rhapsody",
    "Bolt",
    "Bombshell",
    "Boogie Nights",
    "Book of Blood",
    "Booksmart",
    "Boomerang",
    "Born Beautiful",
    "BORUTO -NARUTO THE MOVIE-",
    "Bound by Honor",
    "Bowling for Columbine",
    "Boyka: Undisputed IV",
    "Boże Ciało",
    "Brahms: The Boy II",
    "Brain on Fire",
    "Braindead",
    "Brave",
    "Braveheart",
    "Braven",
    "Brawl in Cell Block 99",
    "Brazil",
    "Breakfast at Tiffany's",
    "Breakthrough",
    "Brick Mansions",
    "Bride & Prejudice",
    "Bride Wars",
    "Bridge of Spies",
    "Bridget Jones: The Edge of Reason",
    "Bridget Jones's Diary",
    "Bright",
    "Brightburn",
    "Brigsby Bear",
    "Brokeback Mountain",
    "Broken Arrow",
    "Broken City",
    "Brooklyn's Finest",
    "Brother Bear",
    "Brother Bear 2",
    "Bruce Almighty",
    "Bucky Larson: Born to Be a Star",
    "Bullet Head",
    "Bullitt",
    "Bumblebee",
    "Burn",
    "Burn After Reading",
    "Butch Cassidy and the Sundance Kid",
    "Butt Boy",
    "By the Sea",
    "Cabin Fever",
    "Cadillac Records",
    "Café Society",
    "Cake",
    "Calendar Girls",
    "Caligola",
    "Caligola: La storia mai raccontata",
    "Call Me by Your Name",
    "Camp Rock 2: The Final Jam",
    "Camp X-Ray",
    "Can You Ever Forgive Me?",
    "Can You Keep a Secret?",
    "Captain America: Civil War",
    "Captain America: The First Avenger",
    "Captain America: The Winter Soldier",
    "Captain Fantastic",
    "Captain Marvel",
    "Captain Phillips",
    "Captain Underpants: The First Epic Movie",
    "Captive State",
    "Carol",
    "Carrie",
    "Cars",
    "Cars 2",
    "Cars 3",
    "Cars Toon Mater's Tall Tales",
    "Casablanca",
    "Casino",
    "Casino Royale",
    "Casper",
    "Cast Away",
    "Castle Freak",
    "Catch Me If You Can",
    "Catch That Kid",
    "Cats",
    "Cats & Dogs",
    "Cats & Dogs: The Revenge of Kitty Galore",
    "Catwoman",
    "Central Intelligence",
    "Certain Women",
    "Chappie",
    "Charlie and the Chocolate Factory",
    "Charlie's Angels",
    "Charlie's Angels: Full Throttle",
    "Charlotte's Web",
    "Cheaper by the Dozen",
    "Chicken Little",
    "Chicken Run",
    "Child 44",
    "Child's Play",
    "Children of Men",
    "Chinatown",
    "CHiPS",
    "Chris D'Elia: No Pain",
    "Christmas Inheritance",
    "Christopher Robin",
    "Chronicle",
    "Chroniques sexuelles d'une famille d'aujourd'hui",
    "Chunky Shrapnel",
    "Cidade de Deus",
    "Cinderella",
    "Cinderella II: Dreams Come True",
    "Cinderella III: A Twist in Time",
    "Citizen Kane",
    "Citizenfour",
    "City Lights",
    "City of Angels",
    "Clash of the Titans",
    "Clear and Present Danger",
    "Cleopatra",
    "Click",
    "Cliffhanger",
    "Climax",
    "Close",
    "Close Encounters of the Third Kind",
    "Close My Eyes",
    "Closed Circuit",
    "Closer",
    "Cloud Atlas",
    "Cloudy with a Chance of Meatballs",
    "Cloudy with a Chance of Meatballs 2",
    "Cloverfield",
    "Clueless",
    "Cobra",
    "Coco",
    "Code 8",
    "Coffee & Kareem",
    "Cold Pursuit",
    "Colette",
    "Collateral",
    "Collateral Beauty",
    "Color Out of Space",
    "Column4",
    "Come and Find Me",
    "Coming to America",
    "Commando",
    "Con Air",
    "Conan the Barbarian",
    "Confessions of a Shopaholic",
    "Conspiracy Theory",
    "Constantine",
    "Contact",
    "Contagion",
    "Contratiempo",
    "Coraline",
    "Corona Zombies",
    "Corpse Bride",
    "Correspondencia",
    "Countdown",
    "Cowboys & Aliens",
    "Coyote Ugly",
    "Crank",
    "Crank: High Voltage",
    "Crash",
    "Crawl",
    "Crazy Rich Asians",
    "Creed",
    "Creed II",
    "Criminal",
    "Crimson Peak",
    "Crossword Mysteries: A Puzzle to Die For",
    "Cube",
    "Cult of Chucky",
    "Curiosa",
    "Curious George",
    "Cursed",
    "D-Tox",
    "Daddy's Home",
    "Daddy's Home 2",
    "Dallas Buyers Club",
    "Dancer in the Dark",
    "Dances with Wolves",
    "Danger Close: The Battle of Long Tan",
    "Dangerous Liaisons",
    "Daredevil",
    "Dark City",
    "Dark Crimes",
    "Dark Phoenix",
    "Dark Places",
    "Dark Shadows",
    "Dark Waters",
    "Darkest Hour",
    "Das Boot",
    "Das Leben der Anderen",
    "David Attenborough: A Life on Our Planet",
    "Dawn of the Dead",
    "Dawn of the Planet of the Apes",
    "Day & Night",
    "Day of the Dead: Bloodline",
    "Daybreakers",
    "De leerling",
    "Dead Poets Society",
    "Deadgirl",
    "Deadpool",
    "Deadpool 2",
    "Dear John",
    "Death Note",
    "Death Proof",
    "Death Race",
    "Death Race: Beyond Anarchy",
    "Death Race: Inferno",
    "Death Sentence",
    "Death Wish",
    "Deep Blue Sea 2",
    "Deep Impact",
    "Deep Rising",
    "Deepwater Horizon",
    "Déjà Vu",
    "Deliver Us from Evil",
    "Demain tout commence",
    "Demolition Man",
    "Den of Thieves",
    "Descendants",
    "Descendants 2",
    "Descendants 3",
    "Desperado",
    "Despicable Me",
    "Despicable Me 2",
    "Despicable Me 3",
    "Destroyer",
    "Det sjunde inseglet",
    "Deux moi",
    "Devil",
    "Devil's Knot",
    "Dial M for Murder",
    "Diamonds Are Forever",
    "Diarios de motocicleta",
    "Die Another Day",
    "Die Getriebenen",
    "Die Hard",
    "Die Hard 2",
    "Die Hard: With a Vengeance",
    "Die unendliche Geschichte",
    "Dinosaur",
    "Dirty Dancing",
    "Dirty Grandpa",
    "Dirty Harry",
    "Disobedience",
    "District 9",
    "Divergent",
    "Django",
    "Django Unchained",
    "Doctor Dolittle",
    "Doctor Sleep",
    "Doctor Strange",
    "DodgeBall: A True Underdog Story",
    "Dogman",
    "Dogville",
    "Dolemite Is My Name",
    "Dolittle",
    "Dolor y gloria",
    "Dolphin Reef",
    "Don Jon",
    "Don't Be a Menace to South Central While Drinking Your Juice in the Hood",
    "Don't Be Afraid of the Dark",
    "Don't Breathe",
    "Don't Look Now",
    "Donnie Brasco",
    "Donnie Darko",
    "Doom",
    "Dora and the Lost City of Gold",
    "Down a Dark Hall",
    "Down to You",
    "Downhill",
    "Downton Abbey",
    "Dr. No",
    "Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb",
    "Dracula",
    "Dracula Untold",
    "Dragonfly",
    "DragonHeart",
    "Dragonheart 3: The Sorcerer's Curse",
    "DragonHeart: A New Beginning",
    "Dragonheart: Battle for the Heartfire",
    "Dragonheart: Vengeance",
    "Dream Horse",
    "Dreamcatcher",
    "Dredd",
    "Drive",
    "Drive Angry",
    "Driven",
    "Dude",
    "Due Date",
    "Dumb and Dumber",
    "Dumb and Dumber To",
    "Dumbo",
    "Dune",
    "Dunkirk",
    "Durante la tormenta",
    "Dying of the Light",
    "E.T. the Extra-Terrestrial",
    "Eagle Eye",
    "Early Man",
    "Earthquake Bird",
    "Eastern Promises",
    "Easy A",
    "Edge of Darkness",
    "Edge of Tomorrow",
    "Edward Scissorhands",
    "Eight Legged Freaks",
    "Eighth Grade",
    "El cadáver de Anna Fritz",
    "El Camino: A Breaking Bad Movie",
    "El hoyo",
    "El laberinto del fauno",
    "El silencio de la ciudad blanca",
    "El silencio del pantano",
    "Elektra",
    "Elephant",
    "Eli",
    "Elizabeth: The Golden Age",
    "Elysium",
    "Emma.",
    "Emmanuelle",
    "En liberté !",
    "En Thangai Kalyani",
    "Enchanted",
    "End of Days",
    "Ender's Game",
    "Endless",
    "Enemy",
    "Enemy at the Gates",
    "Enemy of the State",
    "Enough Said",
    "Entourage",
    "Epic",
    "Equilibrium",
    "Eraser",
    "Eraserhead",
    "Ernest et Célestine",
    "Escape from Alcatraz",
    "Escape from New York",
    "Escape from Pretoria",
    "Escape from the Planet of the Apes",
    "Escape Plan",
    "Escape Plan 2: Hades",
    "Escape Plan: The Extractors",
    "Escape Room",
    "Escobar: Paradise Lost",
    "Eternal Sunshine of the Spotless Mind",
    "EuroTrip",
    "Evan Almighty",
    "Event Horizon",
    "Everest",
    "Every Day",
    "Evil Dead",
    "Evil Dead II",
    "Ewoks: The Battle for Endor",
    "Ex Machina",
    "Exam",
    "Exodus: Gods and Kings",
    "Exotica",
    "Exposed",
    "Extinction",
    "Extraction",
    "Eyes Wide Shut",
    "Face/Off",
    "Fahrenheit 9/11",
    "Fair Game",
    "Fallen",
    "Falling Inn Love",
    "Fame",
    "Fantasia",
    "Fantasia 2000",
    "Fantastic Beasts and Where to Find Them",
    "Fantastic Beasts: The Crimes of Grindelwald",
    "Fantastic Four",
    "Fantastic Four: Rise of the Silver Surfer",
    "Fantastic Mr. Fox",
    "Fantasy Island",
    "Fargo",
    "Fasandræberne",
    "Fast & Furious Presents: Hobbs & Shaw",
    "Faster",
    "Fat Albert",
    "Fatherhood",
    "Favolacce",
    "Fear and Loathing in Las Vegas",
    "Fearless",
    "Fences",
    "Ferdinand",
    "FernGully: The Last Rainforest",
    "Ferris Bueller's Day Off",
    "Field of Dreams",
    "Fifty Shades Darker",
    "Fifty Shades Freed",
    "Fifty Shades of Grey",
    "Fight Club",
    "Fighting with My Family",
    "Final Destination",
    "Final Destination 3",
    "Final Fantasy VII: Advent Children",
    "Final Fantasy: The Spirits Within",
    "Finding Dory",
    "Finding Nemo",
    "Finding Ohana",
    "Firewall",
    "First Blood",
    "First Daughter",
    "First Kill",
    "First Man",
    "First They Killed My Father",
    "Five Feet Apart",
    "Flaskepost fra P",
    "Flight",
    "Flightplan",
    "Flushed Away",
    "Focus",
    "Fool's Gold",
    "For Sama",
    "For Your Eyes Only",
    "Forbidden Planet",
    "Ford v Ferrari",
    "Forever My Girl",
    "Forever Young",
    "Forgetting Sarah Marshall",
    "Forrest Gump",
    "Four Brothers",
    "Four Kids and It",
    "Four Rooms",
    "Fractured",
    "Frankenstein",
    "Freaks",
    "Freddy vs. Jason",
    "Freddy's Dead: The Final Nightmare",
    "Free Solo",
    "Free Willy 2: The Adventure Home",
    "Freedomland",
    "Freier Fall",
    "Friday the 13th",
    "Friday the 13th Part III",
    "Friday the 13th Part VI: Jason Lives",
    "Friday the 13th Part VIII: Jason Takes Manhattan",
    "Friday the 13th: The Final Chapter",
    "Friends with Benefits",
    "From Dusk Till Dawn",
    "From Paris with Love",
    "From Russia with Love",
    "Frozen",
    "Frozen Fever",
    "Frozen II",
    "Fruitvale Station",
    "Full Metal Jacket",
    "Furious 7",
    "Fury",
    "G-Force",
    "G.I. Joe: Retaliation",
    "G.I. Joe: The Rise of Cobra",
    "Galaxy Quest",
    "Game Change",
    "Game Night",
    "Gamer",
    "Gandhi",
    "Gangs of New York",
    "Gangster Squad",
    "Garfield",
    "Garfield: A Tail of Two Kitties",
    "Gattaca",
    "Gemini Man",
    "Geostorm",
    "Gerald's Game",
    "Get a Job",
    "Get Hard",
    "Get Him to the Greek",
    "Get Out",
    "Get the Gringo",
    "Getaway",
    "Ghost",
    "Ghost in the Shell",
    "Ghost Rider",
    "Ghost Rider: Spirit of Vengeance",
    "Ghostbusters",
    "Ghostbusters II",
    "Ghostland",
    "Gifted",
    "Girls Just Want to Have Fun",
    "Gladiator",
    "Glass",
    "Glory",
    "Gnomeo & Juliet",
    "Go!",
    "Gods of Egypt",
    "Godsend",
    "Godzilla",
    "Godzilla: King of the Monsters",
    "Going in Style",
    "Gold Dust",
    "GoldenEye",
    "Goldfinger",
    "Gone Girl",
    "Gone in Sixty Seconds",
    "Gone with the Wind",
    "Good Boys",
    "Good Time",
    "Good Will Hunting",
    "GoodFellas",
    "Goosebumps",
    "Goosebumps 2: Haunted Halloween",
    "Gran Torino",
    "Grandpa Was An Emperor",
    "Gräns",
    "Gravity",
    "Grease",
    "Green Book",
    "Green Lantern",
    "Green Lantern: Emerald Knights",
    "Green Room",
    "Gremlins",
    "Gretel & Hansel",
    "Groundhog Day",
    "Grown Ups",
    "Grown Ups 2",
    "Guardians of the Galaxy",
    "Guardians of the Galaxy Vol. 2",
    "Guns Akimbo",
    "Hachi: A Dog's Tale",
    "Hacksaw Ridge",
    "Hairspray",
    "Hallam Foe",
    "Halloween",
    "Hancock",
    "Handjob Cabin",
    "Hanna",
    "Hansel & Gretel: Witch Hunters",
    "Happily N'Ever After",
    "Happy Death Day",
    "Happy Death Day 2U",
    "Happy Gilmore",
    "Hard Target",
    "Harriet",
    "Harry Potter and the Chamber of Secrets",
    "Harry Potter and the Deathly Hallows: Part 1",
    "Harry Potter and the Deathly Hallows: Part 2",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Philosopher's Stone",
    "Harry Potter and the Prisoner of Azkaban",
    "Haunt",
    "Hawaiian Vacation",
    "Hearts Beat Loud",
    "Heat",
    "Heaven is for Real",
    "Heavy Metal",
    "Hell or High Water",
    "Hellboy",
    "Hellboy II: The Golden Army",
    "Hellraiser",
    "Her",
    "Hercules",
    "Here We Are: Notes for Living on Planet Earth",
    "Hereditary",
    "Hidalgo",
    "Hidden Figures",
    "High Heel Homicide",
    "High Life",
    "High School Musical",
    "High School Musical 3: Senior Year",
    "High Strung",
    "Highlander",
    "Highlander III: The Sorcerer",
    "Highlander: Endgame",
    "Highlander: The Source",
    "Hitch",
    "Hitman",
    "Hitman: Agent 47",
    "Hogar",
    "Hollow Man",
    "Hollow Man II",
    "Hollow Point",
    "Holmes & Watson",
    "Holy Man",
    "Home",
    "Home Again",
    "Home Alone 2: Lost in New York",
    "Home Alone 3",
    "Home Alone 4",
    "Home Alone: The Holiday Heist",
    "Home on the Range",
    "Homefront",
    "Honey",
    "Honey 2",
    "Honey 3: Dare to Dance",
    "Honey Boy",
    "Honey: Rise Up and Dance",
    "Hoodwinked Too! Hood VS. Evil",
    "Hoodwinked!",
    "Hook",
    "Hop",
    "Horrible Bosses",
    "Horrible Bosses 2",
    "Hors Normes",
    "Horse Girl",
    "Hostel",
    "Hostel: Part II",
    "Hostiles",
    "Hot Bot",
    "Hot Fuzz",
    "Hot Girls Wanted",
    "Hot Tub Time Machine",
    "Hotel Artemis",
    "Hotel for Dogs",
    "Hotel Mumbai",
    "Hotel Transylvania",
    "Hotel Transylvania 2",
    "Hotel Transylvania 3: Summer Vacation",
    "House of Wax",
    "How It Ends",
    "How the Grinch Stole Christmas",
    "How to Be a Latin Lover",
    "How to Be Single",
    "How to Train Your Dragon",
    "How to Train Your Dragon 2",
    "How to Train Your Dragon: Homecoming",
    "How to Train Your Dragon: The Hidden World",
    "Hugo",
    "Hulk",
    "Human Capital",
    "Hummingbird",
    "Hunter Killer",
    "Hustlers",
    "I Am Legend",
    "I Am Mother",
    "I Am Not Your Negro",
    "I Am Number Four",
    "I Am Sam",
    "I Am Wrath",
    "I Can Only Imagine",
    "I Know What You Did Last Summer",
    "I Origins",
    "I Spit on Your Grave",
    "I Spit on Your Grave 2",
    "I Spit on Your Grave III: Vengeance is Mine",
    "I Still Believe",
    "I Still Know What You Did Last Summer",
    "I Still See You",
    "Ice Age",
    "Ice Age: A Mammoth Christmas",
    "Ice Age: Collision Course",
    "Ice Age: Continental Drift",
    "Ice Age: Dawn of the Dinosaurs",
    "Ice Age: The Meltdown",
    "Ice Princess",
    "Identity",
    "Idiocracy",
    "Idioterne",
    "Igor",
    "In Bruges",
    "In the Bedroom",
    "In the Blood",
    "In the Heart of the Sea",
    "In the Shadow of the Moon",
    "In the Tall Grass",
    "In the Trap",
    "In Time",
    "Incarnate",
    "Incendies",
    "Inception",
    "Incredibles 2",
    "Independence Day",
    "Independence Day: Resurgence",
    "Indiana Jones and the Kingdom of the Crystal Skull",
    "Indiana Jones and the Last Crusade",
    "Indiana Jones and the Temple of Doom",
    "Inferno",
    "Inglourious Basterds",
    "Inherent Vice",
    "Inside Job",
    "Inside Man",
    "Inside Out",
    "Insidious",
    "Insidious: Chapter 2",
    "Insidious: Chapter 3",
    "Insidious: The Last Key",
    "Instant Family",
    "Insurgent",
    "Intercourse",
    "Interstellar",
    "Interview with the Vampire",
    "Into the Wild",
    "Into the Woods",
    "Intouchables",
    "Invasion of the Body Snatchers",
    "Invictus",
    "Iron Man",
    "Iron Man 2",
    "Iron Man 3",
    "Iron Sky The Coming Race",
    "Irréversible",
    "Isi & Ossi",
    "Isle of Dogs",
    "It",
    "It Chapter Two",
    "It Follows",
    "It Takes Two",
    "It's a Wonderful Life",
    "J'ai perdu mon corps",
    "J’accuse",
    "Jack Reacher",
    "Jack Reacher: Never Go Back",
    "Jack-Jack Attack",
    "Jackass 2.5",
    "Jackass 3.5",
    "Jackass: The Movie",
    "Jackie",
    "Jackie Brown",
    "Jacob's Ladder",
    "Jagten",
    "Jarhead",
    "Jason Bourne",
    "Jaws",
    "Jay and Silent Bob Reboot",
    "Jay and Silent Bob Strike Back",
    "Jeepers Creepers",
    "Jeepers Creepers 2",
    "Jeepers Creepers 3",
    "Jerry Maguire",
    "Jesus Christ Superstar",
    "Jexi",
    "JFK",
    "Jigsaw",
    "Jingle All the Way",
    "Jobs",
    "John Carter",
    "John Tucker Must Die",
    "John Wick",
    "John Wick: Chapter 2",
    "John Wick: Chapter 3 - Parabellum",
    "John Wick: Chapter 4",
    "Johnny English Reborn",
    "Johnny Mnemonic",
    "Jojo Rabbit",
    "Joker",
    "Joseph: King of Dreams",
    "Josie and the Pussycats",
    "Journal 64",
    "Journey 2: The Mysterious Island",
    "Journey to China: The Mystery of Iron Mask",
    "Journey to the Center of the Earth",
    "Judge Dredd",
    "Judy",
    "Judy & Punch",
    "Jumanji: The Next Level",
    "Jumanji: Welcome to the Jungle",
    "Jumper",
    "Jungle",
    "Jungle 2 Jungle",
    "Juno",
    "Jupiter Ascending",
    "Jurassic Galaxy",
    "Jurassic Park",
    "Jurassic World",
    "Jurassic World: Fallen Kingdom",
    "Jusqu'au déclin",
    "Just Go with It",
    "Just Mercy",
    "Justice League",
    "Justice League Dark",
    "Justice League: Crisis on Two Earths",
    "Justice League: War",
    "K-19: The Widowmaker",
    "K-PAX",
    "Kajillionaire",
    "Kama Sutra: A Tale of Love",
    "Kick-Ass",
    "Kick-Ass 2",
    "Kickboxer: Vengeance",
    "Kidnapping Mr. Heineken",
    "Kill Bill: The Whole Bloody Affair",
    "Kill Bill: Vol. 1",
    "Kill Bill: Vol. 2",
    "Killer Elite",
    "Killers",
    "King Arthur",
    "King Arthur: Legend of the Sword",
    "King Kong",
    "King of Thieves",
    "Kingdom of Heaven",
    "Kingsman: The Golden Circle",
    "Kingsman: The Secret Service",
    "Kiss and Kill",
    "Kit Kittredge: An American Girl",
    "Klaus",
    "Knight and Day",
    "Knives Out",
    "Knock Knock",
    "Knocked Up",
    "Knowing",
    "Kong: Skull Island",
    "Kronk's New Groove",
    "Krótki film o miłości",
    "Kubo and the Two Strings",
    "Kung Fu Panda",
    "Kung Fu Panda 2",
    "Kung Fu Panda 3",
    "Kung Fu Panda: Secrets of the Furious Five",
    "Kung Pow: Enter the Fist",
    "Kursk",
    "L.A. Confidential",
    "Labyrinth",
    "Lady and the Tramp",
    "Lady and the Tramp II: Scamp's Adventure",
    "Lady Bird",
    "Lamp Life",
    "Land of the Lost",
    "Lara Croft: Tomb Raider",
    "Last Action Hero",
    "Last Christmas",
    "Lawless",
    "Lawrence of Arabia",
    "Layla Majnun",
    "Leatherface",
    "Leave No Trace",
    "Left Behind",
    "Legend",
    "Legend of the Guardians: The Owls of Ga'Hoole",
    "Legends of Oz: Dorothy's Return",
    "Legends of the Fall",
    "LelleBelle",
    "Lemony Snicket's A Series of Unfortunate Events",
    "Léon: The Professional",
    "Let's Be Cops",
    "Lethal Weapon",
    "Lethal Weapon 3",
    "Lethal Weapon 4",
    "Liar Liar",
    "Licence to Kill",
    "Lie with Me",
    "Life",
    "Life As We Know It",
    "Life Itself",
    "Life of Brian",
    "Life of Crime",
    "Life of Pi",
    "Lights Out",
    "Like a Boss",
    "Lilo & Stitch",
    "Limitless",
    "Lincoln",
    "Lion",
    "Lionheart",
    "Little",
    "Little Black Book",
    "Little Boy",
    "Little Children",
    "Little Fish",
    "Little Fockers",
    "Little Italy",
    "Little Monsters",
    "Little Women",
    "Live and Let Die",
    "Live Free or Die Hard",
    "Lo chiamavano Trinità...",
    "Lo imposible",
    "Lockout",
    "Logan",
    "Logan Lucky",
    "Logan's Run",
    "London Has Fallen",
    "Lone Survivor",
    "Long Shot",
    "Looking for Richard",
    "Looper",
    "Loser",
    "Lost Girls",
    "Lost Highway",
    "Lost in Translation",
    "Louder Than Bombs",
    "Love & Other Drugs",
    "Love Actually",
    "Love Wedding Repeat",
    "Love Wrecked",
    "Loving Pablo",
    "Loving Vincent",
    "Lucky",
    "Lucky Number Slevin",
    "Lucy",
    "Lucy in the Sky",
    "Ma",
    "Ma mère",
    "Machete Kills",
    "Mad Hot Ballroom",
    "Mad Max",
    "Mad Max 2",
    "Mad Max Beyond Thunderdome",
    "Mad Max: Fury Road",
    "Madagascar",
    "Madagascar 3: Europe's Most Wanted",
    "Madagascar: Escape 2 Africa",
    "Made in Senegal",
    "Maggie",
    "Maggie's Plan",
    "Magnolia",
    "Magnum Force",
    "Maladolescenza",
    "Malasaña 32",
    "Maleficent",
    "Maleficent: Mistress of Evil",
    "Malèna",
    "Mamma Mia!",
    "Mamma Mia! Here We Go Again",
    "Man of Steel",
    "Man on Fire",
    "Manchester by the Sea",
    "Mandy",
    "Manhattan Night",
    "Marauders",
    "Marie Antoinette",
    "Marley",
    "Marmaduke",
    "Marnie",
    "Marriage Story",
    "Mars Attacks!",
    "Martyrs",
    "Mary",
    "Mary Magdalene",
    "Mary Poppins",
    "Mary Poppins Returns",
    "Mary Queen of Scots",
    "Mary Shelley",
    "Master and Commander: The Far Side of the World",
    "Materna",
    "Matthias & Maxime",
    "Max",
    "Max Payne",
    "Max Steel",
    "Maze Runner: The Death Cure",
    "Maze Runner: The Scorch Trials",
    "Me Before You",
    "Mean Girls",
    "Mean Girls 2",
    "Mechanic: Resurrection",
    "Meet Joe Black",
    "Meet the Fockers",
    "Meet the Parents",
    "Meet the Robinsons",
    "Meet the Spartans",
    "Megamind",
    "Megan Leavey",
    "Meine teuflisch gute Freundin",
    "Melissa P.",
    "Memento",
    "Memoirs of a Geisha",
    "Men in Black",
    "Men in Black 3",
    "Men in Black II",
    "Men in Black: International",
    "Men of Honor",
    "Mentiras y gordas",
    "Metro",
    "Metropolis",
    "Mia",
    "Mia et le lion blanc",
    "mid90s",
    "Midnight in Paris",
    "Midnight Sun",
    "Midsommar",
    "Midway",
    "Mike and Dave Need Wedding Dates",
    "Mike's New Car",
    "Mile 22",
    "Milea: Suara dari Dilan",
    "Milk Money",
    "Miller's Crossing",
    "Million Dollar Baby",
    "Min farmors hus",
    "Mine",
    "Minority Report",
    "Miracles from Heaven",
    "Mirror Mirror",
    "Mirrors",
    "Miss Americana",
    "Miss Bala",
    "Miss Congeniality 2: Armed and Fabulous",
    "Miss Fisher and the Crypt of Tears",
    "Miss Peregrine's Home for Peculiar Children",
    "Missing Link",
    "Mission: Impossible",
    "Mission: Impossible - Fallout",
    "Mission: Impossible - Ghost Protocol",
    "Mission: Impossible - Rogue Nation",
    "Mission: Impossible II",
    "Mission: Impossible III",
    "Modern Times",
    "Molly's Game",
    "Mom and Dad",
    "Momentum",
    "Money Monster",
    "Monster House",
    "Monster Trucks",
    "Monsters University",
    "Monsters vs Aliens",
    "Monty Python and the Holy Grail",
    "Moon",
    "Moonlight",
    "Moonraker",
    "Moonrise Kingdom",
    "Morning Glory",
    "Mortal Engines",
    "Mortal Kombat",
    "Mortal Kombat Legends: Scorpion’s Revenge",
    "Mortal Kombat: Annihilation",
    "Mortdecai",
    "mother!",
    "Motherless Brooklyn",
    "Moulin Rouge!",
    "Mowgli: Legend of the Jungle",
    "Mr. & Mrs. Smith",
    "Mr. Bean's Holiday",
    "Mr. Holmes",
    "Mr. Peabody & Sherman",
    "Mrs. Doubtfire",
    "Mucize 2: Aşk",
    "Mudik",
    "Mulan",
    "Mulan II",
    "Mulholland Drive",
    "Murder Mystery",
    "Murder on the Orient Express",
    "Music and Lyrics",
    "My Cousin Rachel",
    "My Little Pony: The Movie",
    "My Spy",
    "Mystic River",
    "Naked",
    "Naked Gun 33⅓: The Final Insult",
    "Nanny McPhee",
    "Nater Guru",
    "National Treasure",
    "National Treasure: Book of Secrets",
    "Natural Born Killers",
    "Nature of Love",
    "Neighbors",
    "Neighbors 2: Sorority Rising",
    "Nerve",
    "Never Back Down",
    "Never Back Down 2: The Beatdown",
    "Never Back Down: No Surrender",
    "Never Rarely Sometimes Always",
    "Never Say Never Again",
    "New Year's Eve",
    "Newness",
    "Next",
    "Next Friday",
    "Nezha: Birth of the Demon Child",
    "Nick and Norah's Infinite Playlist",
    "Night at the Museum",
    "Night at the Museum: Battle of the Smithsonian",
    "Night at the Museum: Secret of the Tomb",
    "Night Hunter",
    "Night of the Living Dead",
    "Nightcrawler",
    "Nightmare Cinema",
    "Nine 1/2 Weeks",
    "No Country for Old Men",
    "No Good Deed",
    "No Strings Attached",
    "No Time to Die",
    "Nocturnal Animals",
    "Norbit",
    "Norm of the North",
    "Normal",
    "North by Northwest",
    "Notting Hill",
    "Now You See Me",
    "Now You See Me 2",
    "Nuovo Cinema Paradiso",
    "Nutty Professor II: The Klumps",
    "Nymphomaniac: Vol. II",
    "Oblivion",
    "Ocean's Eight",
    "Ocean's Eleven",
    "Ocean's Thirteen",
    "Ocean's Twelve",
    "Octopussy",
    "Official Secrets",
    "Olaf's Frozen Adventure",
    "Old School",
    "Oldboy",
    "Oliver & Company",
    "Olympus Has Fallen",
    "On Her Majesty's Secret Service",
    "On the Basis of Sex",
    "On the Waterfront",
    "Once",
    "Once Upon a Deadpool",
    "Once Upon a Time in America",
    "Once Upon a Time… in Hollywood",
    "One Day",
    "One Flew Over the Cuckoo's Nest",
    "One Hundred and One Dalmatians",
    "Onward",
    "Open Season",
    "Ordinary Love",
    "Original Sin",
    "Orphan",
    "Otryv",
    "Ouija",
    "Ouija: Origin of Evil",
    "Our Kind of Traitor",
    "Out of the Furnace",
    "Outbreak",
    "Outcast",
    "Outlaw King",
    "Over the Hedge",
    "Overboard",
    "Overdrive",
    "Overlord",
    "P.S. I Love You",
    "P2",
    "Pacific Rim",
    "Pacific Rim: Uprising",
    "Paddington",
    "Paddington 2",
    "Pain & Gain",
    "Palmeras en la nieve",
    "Pan",
    "Pandorum",
    "Panic Room",
    "Papillon",
    "Paprika",
    "Paradise Hills",
    "Paranormal Activity",
    "Paranormal Activity 4",
    "Passenger 57",
    "Passengers",
    "Paths of Glory",
    "Patriot Games",
    "Patriots Day",
    "Patton",
    "Paul",
    "Paul Blart: Mall Cop",
    "Paul Blart: Mall Cop 2",
    "Pay It Forward",
    "Payback",
    "Pearl Harbor",
    "Penguins of Madagascar",
    "Peppermint",
    "Percy Jackson & the Olympians: The Lightning Thief",
    "Persian Lessons",
    "Persona",
    "Pet Sematary",
    "Pete's Dragon",
    "Peter Pan",
    "Peter Rabbit",
    "Phantom Thread",
    "Phantoms",
    "Pink Floyd: The Wall",
    "Pinocchio",
    "Pirates of the Caribbean: At World's End",
    "Pirates of the Caribbean: Dead Man's Chest",
    "Pirates of the Caribbean: Dead Men Tell No Tales",
    "Pirates of the Caribbean: On Stranger Tides",
    "Pirates of the Caribbean: The Curse of the Black Pearl",
    "Pitch Perfect",
    "Pitch Perfect 2",
    "Pitch Perfect 3",
    "Pixels",
    "Planet of the Apes",
    "Planet Terror",
    "Platoon",
    "Playdate with Destiny",
    "Playing It Cool",
    "Playing with Fire",
    "Pocahontas",
    "Point Break",
    "Pokémon Detective Pikachu",
    "Polar",
    "Police Academy",
    "Police Academy 2: Their First Assignment",
    "Police Academy 4: Citizens on Patrol",
    "Police Academy 6: City Under Siege",
    "Poltergeist",
    "Poltergeist III",
    "Popstar: Never Stop Never Stopping",
    "Porno",
    "Powder",
    "Power Rangers",
    "Prayers for Bobby",
    "Precious Cargo",
    "Predator",
    "Predator 2",
    "Predators",
    "Predestination",
    "Premonition",
    "Pretty Little Stalker",
    "Pretty Woman",
    "Pride & Prejudice",
    "Primary Colors",
    "Prime",
    "Primer",
    "Prince of Darkness",
    "Prince of Persia: The Sands of Time",
    "Prisoners",
    "Private Lessons",
    "Professor Marston and the Wonder Women",
    "Prometheus",
    "Prospect",
    "Proxima",
    "Psycho",
    "Pulp Fiction",
    "Push",
    "Puss in Boots: The Three Diablos",
    "Q",
    "Quantum of Solace",
    "Quarantine",
    "Quarantine 2: Terminal",
    "Queen & Slim",
    "Queen of the Damned",
    "Quest for Camelot",
    "Quien a hierro mata",
    "Race to Witch Mountain",
    "Raging Bull",
    "Raiders of the Lost Ark",
    "Rain Man",
    "Raising Arizona",
    "Ralph Breaks the Internet",
    "Rambo",
    "Rambo III",
    "Rambo: First Blood Part II",
    "Rambo: Last Blood",
    "Rampage",
    "Rango",
    "Ransom",
    "Ratatouille",
    "Ratchet & Clank",
    "Ray",
    "Ready or Not",
    "Ready Player One",
    "Real Steel",
    "Rear Window",
    "Rebound",
    "RED",
    "RED 2",
    "Red Heat",
    "Red Joan",
    "Red Shoes and the Seven Dwarfs",
    "Red Sparrow",
    "Regression",
    "Reign of Fire",
    "Reign of the Supermen",
    "Relatos salvajes",
    "Remember Me",
    "Remember the Titans",
    "Renegades",
    "Replicas",
    "Reprisal",
    "Reservoir Dogs",
    "Resident Evil",
    "Resistance",
    "Return of the Jedi",
    "Return to Never Land",
    "Revenge",
    "Revolutionary Road",
    "Ri¢hie Ri¢h",
    "Richard Jewell",
    "Riddick",
    "Ride",
    "Ride Along",
    "Ride Along 2",
    "Rio",
    "Rio 2",
    "Rise of the Guardians",
    "Rise of the Planet of the Apes",
    "Risen",
    "Road to Ninja: Naruto the Movie",
    "Road to Perdition",
    "Robin Hood",
    "Robin Hood: Prince of Thieves",
    "RoboCop",
    "RoboCop 2",
    "Robots",
    "Rock Dog",
    "Rock the Kasbah",
    "Rocketman",
    "Rocky",
    "Rocky Balboa",
    "Rocky III",
    "Rocky IV",
    "Rocky V",
    "Rogue One: A Star Wars Story",
    "Roma",
    "Romance",
    "Romancing the Stone",
    "Romeo + Juliet",
    "Romeo Must Die",
    "Ronin",
    "Room",
    "Rosemary's Baby",
    "Rudolph the Red-Nosed Reindeer",
    "Rugrats in Paris: The Movie",
    "Rules Don't Apply",
    "Run All Night",
    "Rush Hour",
    "Russkaya Lolita",
    "S. Darko",
    "S.W.A.T.",
    "Safe House",
    "Salmon Fishing in the Yemen",
    "Salt",
    "Same Kind of Different as Me",
    "Samson and Delilah",
    "San Andreas",
    "Sand Castle",
    "Sandy Wexler",
    "Saphirblau",
    "Saturday Night Fever",
    "Sausage Party",
    "Saving Private Ryan",
    "Saw",
    "Saw 3D",
    "Saw II",
    "Saw III",
    "Saw IV",
    "Saw V",
    "Saw VI",
    "Scarface",
    "Scary Movie",
    "Scary Movie 2",
    "Scary Movie 3",
    "Scary Movie 4",
    "Scary Movie 6",
    "Scary Stories to Tell in the Dark",
    "Schindler's List",
    "School of Rock",
    "Scooby-Doo",
    "Scooby-Doo 2: Monsters Unleashed",
    "Scott Pilgrim vs. the World",
    "Scream",
    "Scream 2",
    "Scream 4",
    "Se7en",
    "Sea Fever",
    "Searching",
    "Season of Love",
    "Season of the Witch",
    "Seberg",
    "Secret Obsession",
    "Secret of the Wings",
    "Secret Society of Second Born Royals",
    "Secret Window",
    "Security",
    "Self/less",
    "Sense and Sensibility",
    "Serbuan maut",
    "Serena",
    "Serenity",
    "Sergio",
    "Seventh Son",
    "Sex Tape",
    "Sex Weather",
    "Sextuplets",
    "Shaft",
    "Shark Tale",
    "Shaun of the Dead",
    "Shazam!",
    "Sherlock Gnomes",
    "Sherlock Holmes",
    "Sherlock Holmes: A Game of Shadows",
    "Shifshuf Naim",
    "Shivers",
    "Shooter",
    "Shopgirl",
    "Shot Caller",
    "Shrek",
    "Shrek 2",
    "Shrek Forever After",
    "Shrek the Third",
    "Shut In",
    "Shutter Island",
    "Siberia",
    "Sicario",
    "Sicario: Day of the Soldado",
    "Signs",
    "Silence",
    "Silent Hill: Revelation 3D",
    "Silk",
    "Silver Linings Playbook",
    "Sin City",
    "Sin City: A Dame to Kill For",
    "Sinbad: Legend of the Seven Seas",
    "Sing",
    "Sing Street",
    "Singin' in the Rain",
    "Sinister",
    "Sinister 2",
    "Sinister Seduction",
    "Sister Act 2: Back in the Habit",
    "Sixteen Candles",
    "Skjelvet",
    "Skyfall",
    "Skyscraper",
    "Sleeping Beauty",
    "Sleeping with Other People",
    "Sleepless in Seattle",
    "Sleepy Hollow",
    "Sleuth",
    "Slumdog Millionaire",
    "Smallfoot",
    "Smultronstället",
    "Smurfs: The Lost Village",
    "Snatch",
    "Sniper",
    "Sniper: Ultimate Kill",
    "Snow White and the Huntsman",
    "Snow White and the Seven Dwarfs",
    "Snowpiercer",
    "Soapdish",
    "Solo: A Star Wars Story",
    "Some Kind of Beautiful",
    "Some Like It Hot",
    "Son of the Mask",
    "Sonic the Hedgehog",
    "Sorry to Bother You",
    "Sorry We Missed You",
    "Soul",
    "Source Code",
    "Southbound",
    "Southpaw",
    "Space Jam",
    "Spaceballs",
    "Species",
    "Species III",
    "Spectre",
    "Speed",
    "Spenser Confidential",
    "Sphere",
    "Spider-Man",
    "Spider-Man 3",
    "Spider-Man: Far from Home",
    "Spider-Man: Homecoming",
    "Spider-Man: Into the Spider-Verse",
    "Spies in Disguise",
    "Spirit: Stallion of the Cimarron",
    "Splash",
    "Split",
    "Spotlight",
    "Spring Breakers",
    "Spy",
    "St. Vincent",
    "Stan & Ollie",
    "Stand by Me",
    "Star Trek",
    "Star Trek Beyond",
    "Star Trek Into Darkness",
    "Star Trek IV: The Voyage Home",
    "Star Trek V: The Final Frontier",
    "Star Trek: First Contact",
    "Star Trek: Nemesis",
    "Star Trek: The Motion Picture",
    "Star Wars: Episode I - The Phantom Menace",
    "Star Wars: Episode II - Attack of the Clones",
    "Star Wars: Episode III - Revenge of the Sith",
    "Star Wars: The Clone Wars",
    "Star Wars: The Force Awakens",
    "Star Wars: The Last Jedi",
    "Star Wars: The Rise of Skywalker",
    "Stardust",
    "Stargate",
    "Stargirl",
    "Starship Troopers",
    "Starship Troopers 3: Marauder",
    "Starship Troopers: Invasion",
    "Starstruck",
    "Step Up",
    "Step Up 2: The Streets",
    "Step Up 3D",
    "Step Up All In",
    "Step Up Revolution",
    "Steven Universe: The Movie",
    "Stitch! The Movie",
    "Stonehearst Asylum",
    "Storks",
    "Straight Outta Compton",
    "Street Fighter",
    "Street Kings",
    "StreetDance 2",
    "StreetDance 3D",
    "Stuart Little",
    "Stuart Little 3: Call of the Wild",
    "Stuber",
    "Sub Rosa",
    "Suburbicon",
    "Sucker Punch",
    "Suicide Squad",
    "Suite Française",
    "Sullivan's Travels",
    "Sully",
    "Summerland",
    "Sunset Boulevard",
    "Sunshine",
    "Super 8",
    "Superbad",
    "Superintelligence",
    "Superman",
    "Superman II",
    "Superman Returns",
    "Superman: Red Son",
    "Surf's Up",
    "Surrogates",
    "Survivor",
    "Suspiria",
    "Swallow",
    "Sweeney Todd: The Demon Barber of Fleet Street",
    "Tag",
    "Taken",
    "Taken 2",
    "Taken 3",
    "Takers",
    "Tales From Six Feet Under",
    "Tall Girl",
    "Tamara Drewe",
    "Tangled",
    "Tarzan",
    "Tarzan & Jane",
    "Tarzan II",
    "Taxi",
    "Taxi 2",
    "Taxi Driver",
    "Tears of the Sun",
    "Ted",
    "Ted 2",
    "Teen Beach 2",
    "Teen Beach Movie",
    "Teen Titans Go! To the Movies",
    "Teen Titans Go! vs. Teen Titans",
    "Teen Titans: The Judas Contract",
    "Teenage Mutant Ninja Turtles",
    "Teenage Mutant Ninja Turtles: Out of the Shadows",
    "Tenet",
    "Terminator 2: Judgment Day",
    "Terminator 3: Rise of the Machines",
    "Terminator Genisys",
    "Terminator Salvation",
    "Terminator: Dark Fate",
    "Texas Chainsaw 3D",
    "That's My Boy",
    "The 'Burbs",
    "The 13th Warrior",
    "The 40 Year Old Virgin",
    "The 5th Wave",
    "The A-Team",
    "The Abyss",
    "The Accountant",
    "The Addams Family",
    "The Adjustment Bureau",
    "The Adventures of Ichabod and Mr. Toad",
    "The Adventures of Sharkboy and Lavagirl",
    "The Adventures of Tintin",
    "The Aeronauts",
    "The Aftermath",
    "The Age of Adaline",
    "The Amazing Spider-Man",
    "The Amazing Spider-Man 2",
    "The Angry Birds Movie",
    "The Angry Birds Movie 2",
    "The Animatrix",
    "The Apartment",
    "The Aristocats",
    "The Autopsy of Jane Doe",
    "The Avengers",
    "The Aviator",
    "The Babadook",
    "The Babysitter",
    "The Babysitters",
    "The Ballad of Buster Scruggs",
    "The Bank Job",
    "The Banker",
    "The Basketball Diaries",
    "The Belko Experiment",
    "The Best of Enemies",
    "The BFG",
    "The Big Lebowski",
    "The Big Short",
    "The Big Sick",
    "The Birds",
    "The Birth of a Nation",
    "The Black Cauldron",
    "The Black Hole",
    "The Blackcoat's Daughter",
    "The Blind Side",
    "The Blues Brothers",
    "The Bodyguard",
    "The Book of Eli",
    "The Book of Life",
    "The Bounty",
    "The Bourne Identity",
    "The Bourne Legacy",
    "The Bourne Supremacy",
    "The Bourne Ultimatum",
    "The Boxtrolls",
    "The Boy",
    "The Boy in the Striped Pyjamas",
    "The Boy Who Harnessed the Wind",
    "The Breakfast Club",
    "The Breed",
    "The Bridge on the River Kwai",
    "The Brown Bunny",
    "The Butterfly Effect",
    "The Butterfly Effect 3: Revelations",
    "The Bye Bye Man",
    "The Cabin in the Woods",
    "The Call of the Wild",
    "The Captive",
    "The Catcher Was a Spy",
    "The Choice",
    "The Chronicles of Narnia: Prince Caspian",
    "The Chronicles of Narnia: The Voyage of the Dawn Treader",
    "The Circle",
    "The Coldest Game",
    "The Collection",
    "The Collector",
    "The Color Purple",
    "The Commuter",
    "The Conjuring",
    "The Conjuring 2",
    "The Contract",
    "The Conversation",
    "The Core",
    "The Counselor",
    "The Croods",
    "The Crow",
    "The Crucifixion",
    "The Curious Case of Benjamin Button",
    "The Current War",
    "The Curse of La Llorona",
    "The Da Vinci Code",
    "The Danish Girl",
    "The Dark and the Wicked",
    "The Dark Knight",
    "The Dark Knight Rises",
    "The Dark Tower",
    "The Dating List",
    "The Day After Tomorrow",
    "The Day the Earth Stood Still",
    "The Dead Pool",
    "The Deer Hunter",
    "The Departed",
    "The Descent",
    "The Devil Wears Prada",
    "The Devil's Advocate",
    "The Dictator",
    "The Disaster Artist",
    "The Dreamers",
    "The Drop",
    "The DUFF",
    "The Duke",
    "The Dukes of Hazzard: The Beginning",
    "The Eagle",
    "The Eagle Huntress",
    "The Education of Fredrick Fitzell",
    "The Emoji Movie",
    "The Emperor's New Groove",
    "The Empire Strikes Back",
    "The Equalizer",
    "The Equalizer 2",
    "The Escort",
    "The Evil Dead",
    "The Exorcist",
    "The Expendables",
    "The Expendables 2",
    "The Expendables 3",
    "The Faculty",
    "The Farewell",
    "The Fate of the Furious",
    "The Fault in Our Stars",
    "The Favourite",
    "The Fifth Element",
    "The Fight for Pollard Hatch",
    "The Fighter",
    "The Final Destination",
    "The Finest Hours",
    "The First Purge",
    "The Flintstones",
    "The Flintstones in Viva Rock Vegas",
    "The Foreigner",
    "The Founder",
    "The Fox and the Hound",
    "The Fox and the Hound 2",
    "The French Connection",
    "The Front Runner",
    "The Fugitive",
    "The Gallows",
    "The Game",
    "The Game Changers",
    "The General",
    "The Genesis Children",
    "The Gentlemen",
    "The Getaway",
    "The Ghost Writer",
    "The Girl in the Spider's Web",
    "The Girl Next Door",
    "The Girl on the Train",
    "The Girl with All the Gifts",
    "The Girl with the Dragon Tattoo",
    "The Giver",
    "The Godfather",
    "The Godfather: Part II",
    "The Godfather: Part III",
    "The Gods Must Be Crazy",
    "The Gods Must Be Crazy II",
    "The Golden Compass",
    "The Goldfinch",
    "The Good Dinosaur",
    "The Good Doctor",
    "The Good Liar",
    "The Good Neighbor",
    "The Good Shepherd",
    "The Goonies",
    "The Graduate",
    "The Grand Budapest Hotel",
    "The Great Debaters",
    "The Great Dictator",
    "The Great Escape",
    "The Great Gatsby",
    "The Great Raid",
    "The Great Wall",
    "The Greatest Showman",
    "The Green Hornet",
    "The Green Mile",
    "The Grey",
    "The Grinch",
    "The Grudge",
    "The Grudge 2",
    "The Guilt Trip",
    "The Gunman",
    "The Hangover",
    "The Hangover Part II",
    "The Hangover Part III",
    "The Happening",
    "The Happytime Murders",
    "The Hate U Give",
    "The Hateful Eight",
    "The Healer",
    "The Help",
    "The High Note",
    "The Highwaymen",
    "The Hills Have Eyes",
    "The Hills Have Eyes II",
    "The Hitchhiker's Guide to the Galaxy",
    "The Hitman's Bodyguard",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Battle of the Five Armies",
    "The Hobbit: The Desolation of Smaug",
    "The Hole in the Ground",
    "The House Bunny",
    "The House That Jack Built",
    "The House with a Clock in Its Walls",
    "The Howling",
    "The Hummingbird Project",
    "The Hunchback of Notre Dame",
    "The Hunchback of Notre Dame II",
    "The Hunger Games",
    "The Hunger Games: Catching Fire",
    "The Hunger Games: Mockingjay - Part 1",
    "The Hunger Games: Mockingjay - Part 2",
    "The Hunt",
    "The Hunt for Red October",
    "The Hunter's Prayer",
    "The Huntsman: Winter's War",
    "The Hurricane Heist",
    "The Hurt Locker",
    "The Hustle",
    "The I Inside",
    "The Illusionist",
    "The Imitation Game",
    "The Incredible Hulk",
    "The Incredibles",
    "The Informer",
    "The Informers",
    "The Intern",
    "The International",
    "The Interview",
    "The Intruder",
    "The Invisible Man",
    "The Irishman",
    "The Iron Giant",
    "The Island",
    "The Italian Job",
    "The Jackal",
    "The Judge",
    "The Jungle Book",
    "The Jungle Book 2",
    "The Karate Kid",
    "The Killing of a Sacred Deer",
    "The King",
    "The King and I",
    "The King's Man",
    "The King's Speech",
    "The Kingdom",
    "The Kissing Booth",
    "The Kitchen",
    "The Knight Before Christmas",
    "The Land Before Time",
    "The Land Before Time: The Great Valley Adventure",
    "The Last Airbender",
    "The Last Emperor",
    "The Last Face",
    "The Last Full Measure",
    "The Last Legion",
    "The Last of the Mohicans",
    "The Last Samurai",
    "The Last Stand",
    "The Last Summer",
    "The Last Thing He Wanted",
    "The Last Witch Hunter",
    "The Last: Naruto the Movie",
    "The Laundromat",
    "The Layover",
    "The Lazarus Effect",
    "The League of Extraordinary Gentlemen",
    "The Legend of Hercules",
    "The Legend of Tarzan",
    "The Legend of Zorro",
    "The Lego Batman Movie",
    "The Lego Movie",
    "The Lego Movie 2: The Second Part",
    "The Lego Ninjago Movie",
    "The Librarian: Quest for the Spear",
    "The Librarian: Return to King Solomon's Mines",
    "The Light Between Oceans",
    "The Lighthouse",
    "The Lion King",
    "The Lion King 1½",
    "The Lion King II: Simba's Pride",
    "The Little Mermaid",
    "The Little Prince",
    "The Living Daylights",
    "The Lobster",
    "The Loft",
    "The Lone Ranger",
    "The Longest Ride",
    "The Longest Week",
    "The Look of Silence",
    "The Lorax",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Two Towers",
    "The Lost City of Z",
    "The Love Punch",
    "The Lucky One",
    "The Machinist",
    "The Magnificent Seven",
    "The Main Event",
    "The Man from U.N.C.L.E.",
    "The Man in the Iron Mask",
    "The Man Who Knew Infinity",
    "The Man Who Knew Too Much",
    "The Man with the Golden Gun",
    "The Man with the Iron Heart",
    "The Martian",
    "The Mask",
    "The Matrix",
    "The Matrix Reloaded",
    "The Matrix Revolutions",
    "The Maze Runner",
    "The Mechanic",
    "The Meg",
    "The Miseducation of Cameron Post",
    "The Mist",
    "The Mortal Instruments: City of Bones",
    "The Mule",
    "The Mummy",
    "The Mummy Returns",
    "The Mummy: Tomb of the Dragon Emperor",
    "The Musketeer",
    "The Naked Gun 2½: The Smell of Fear",
    "The Naked Gun: From the Files of Police Squad!",
    "The Namesake",
    "The Negotiator",
    "The Neon Demon",
    "The NeverEnding Story II: The Next Chapter",
    "The Next Three Days",
    "The Nice Guys",
    "The Night Clerk",
    "The Nightmare Before Christmas",
    "The Notebook",
    "The November Man",
    "The Nun",
    "The Nutcracker and the Four Realms",
    "The Nutty Professor",
    "The Omen",
    "The One",
    "The Order",
    "The Osiris Child",
    "The Other Boleyn Girl",
    "The Other Lamb",
    "The Other Side of the Door",
    "The Pacifier",
    "The Pagemaster",
    "The Panti Sisters",
    "The Parent Trap",
    "The Party at Kitty and Stud's",
    "The Passion of the Christ",
    "The Patriot",
    "The Peanut Butter Falcon",
    "The Perfect Date",
    "The Perks of Being a Wallflower",
    "The Physician",
    "The Pianist",
    "The Pink Panther",
    "The Place Beyond the Pines",
    "The Player",
    "The Poison Rose",
    "The Possession of Hannah Grace",
    "The Post",
    "The Postcard Killings",
    "The Predator",
    "The Prestige",
    "The Prince",
    "The Prince of Egypt",
    "The Princess and the Frog",
    "The Princess Bride",
    "The Princess Diaries",
    "The Princess Diaries 2: Royal Engagement",
    "The Princess Switch",
    "The Prodigy",
    "The Producers",
    "The Professor",
    "The Professor and the Madman",
    "The Proposal",
    "The Punisher",
    "The Purge",
    "The Purge: Anarchy",
    "The Purge: Election Year",
    "The Pursuit of Happyness",
    "The Queen's Corgi",
    "The Quest",
    "The Quiet",
    "The Reader",
    "The Recruit",
    "The Red Pill",
    "The Red Sea Diving Resort",
    "The Red Shoes",
    "The Report",
    "The Rescuers",
    "The Return of Jafar",
    "The Revenant",
    "The Rhythm Section",
    "The Ridiculous 6",
    "The Ring",
    "The Roads Not Taken",
    "The Rock",
    "The Room",
    "The Roommate",
    "The Running Man",
    "The Sacred Riana: Beginning",
    "The Sand",
    "The Scorpion King",
    "The Scorpion King 2: Rise of a Warrior",
    "The Scorpion King 3: Battle for Redemption",
    "The Scorpion King: Book of Souls",
    "The Searchers",
    "The Secret Life of Pets 2",
    "The Secret Life of Walter Mitty",
    "The Secret: Dare to Dream",
    "The Shack",
    "The Shape of Water",
    "The Shawshank Redemption",
    "The Shining",
    "The Siege of Jadotville",
    "The Silence",
    "The Simpsons Movie",
    "The Sixth Sense",
    "The Skeleton Key",
    "The Smurfs",
    "The Smurfs 2",
    "The Snow Walker",
    "The Social Network",
    "The Sorcerer's Apprentice",
    "The Sound of Music",
    "The SpongeBob Movie: Sponge Out of Water",
    "The SpongeBob SquarePants Movie",
    "The Spy Who Dumped Me",
    "The Spy Who Loved Me",
    "The Star",
    "The Sum of All Fears",
    "The Sword in the Stone",
    "The Tale",
    "The Talented Mr. Ripley",
    "The Ten Commandments",
    "The Terminal",
    "The Terminator",
    "The Texas Chainsaw Massacre",
    "The Theory of Everything",
    "The Thin Red Line",
    "The Thing",
    "The Tourist",
    "The Transporter",
    "The Transporter Refueled",
    "The Treasure of the Sierra Madre",
    "The Truman Show",
    "The Turning",
    "The Tuxedo",
    "The Twilight Saga: Breaking Dawn - Part 1",
    "The Twilight Saga: Breaking Dawn - Part 2",
    "The Twilight Saga: Eclipse",
    "The Twilight Saga: New Moon",
    "The Two Popes",
    "The Ugly Truth",
    "The Untouchables",
    "The Upside",
    "The Usual Suspects",
    "The Vanishing",
    "The Violent Heart",
    "The Virgin Suicides",
    "The Visit",
    "The Vow",
    "The Walk",
    "The Watch",
    "The Way Back",
    "The Wedding Ringer",
    "The Whole Nine Yards",
    "The Whole Ten Yards",
    "The Wild",
    "The Wind Walker",
    "The Witch",
    "The Wizard of Oz",
    "The Wolf of Wall Street",
    "The Woman in Black",
    "The Words",
    "The World Is Not Enough",
    "The World's End",
    "The Young Victoria",
    "Their Finest",
    "There Will Be Blood",
    "There's Something About Mary",
    "They Live",
    "Thir13en Ghosts",
    "This Is the End",
    "Thor",
    "Thor: Ragnarok",
    "Thor: The Dark World",
    "Three",
    "Thumbelina",
    "Thunderball",
    "Thunderstruck",
    "Tigertail",
    "Timecop",
    "Timeline",
    "Timmy Failure: Mistakes Were Made",
    "Timmy's Cinema Adventure",
    "Tinker Bell",
    "Tinker Bell and the Great Fairy Rescue",
    "Tinker Bell and the Legend of the NeverBeast",
    "Tinker Bell and the Lost Treasure",
    "Tinker Bell and the Pirate Fairy",
    "Tinker Tailor Soldier Spy",
    "Titanic",
    "TMNT",
    "To All the Boys I've Loved Before",
    "To All the Boys: P.S. I Still Love You",
    "To Kill a Mockingbird",
    "To Plant a Flag",
    "Togo",
    "Tolkien",
    "Tomb Raider",
    "Tombstone",
    "Tomorrow Never Dies",
    "Tomorrowland",
    "Too Big to Fail",
    "Tooth Fairy",
    "Top Gun",
    "Top Gun: Maverick",
    "Torque",
    "Total Recall",
    "Toy Story",
    "Toy Story 2",
    "Toy Story 3",
    "Toy Story 4",
    "Toy Story That Time Forgot",
    "Tracers",
    "Traffic",
    "Traffik",
    "Training Day",
    "Trainspotting",
    "Trainwreck",
    "Transcendence",
    "Transformers: Age of Extinction",
    "Transformers: The Last Knight",
    "Transporter 2",
    "Transporter 3",
    "Trauma Center",
    "Treasure Planet",
    "Tremors",
    "Tremors 2: Aftershocks",
    "Tremors 3: Back to Perfection",
    "Tremors 4: The Legend Begins",
    "Tremors 5: Bloodlines",
    "Tremors: A Cold Day in Hell",
    "Triangle",
    "Triple 9",
    "Triple Frontier",
    "Triple Threat",
    "Trolls",
    "Trolls World Tour",
    "TRON: Legacy",
    "Tropa de Elite",
    "Tropic Thunder",
    "Trouble",
    "Troy",
    "True Grit",
    "True Lies",
    "True Memoirs of an International Assassin",
    "True Romance",
    "Truth",
    "Truth or Dare",
    "Tucker and Dale vs. Evil",
    "Turbo",
    "Twelve Monkeys",
    "Twilight",
    "Twin Peaks: Fire Walk with Me",
    "Twins",
    "Twisted",
    "Twister",
    "Two Night Stand",
    "UglyDolls",
    "Ultimate Avengers",
    "Ultras",
    "Ultraviolet",
    "Un figlio di nome Erasmus",
    "Unbreakable",
    "Unbroken",
    "Uncorked",
    "Uncut Gems",
    "Under Siege",
    "Under the Silver Lake",
    "Under the Tuscan Sun",
    "Underwater",
    "Underworld",
    "Underworld: Awakening",
    "Underworld: Blood Wars",
    "Underworld: Rise of the Lycans",
    "Undisputed",
    "Undisputed II: Last Man Standing",
    "Undisputed III: Redemption",
    "Une vraie jeune fille",
    "Unfaithful",
    "Unforgiven",
    "Unhinged",
    "Universal Soldier: Day of Reckoning",
    "Unknown",
    "Unstoppable",
    "Unthinkable",
    "Untitled Spider-Man 3",
    "Up",
    "Up in the Air",
    "Upgrade",
    "Urban Legends: Final Cut",
    "Us",
    "USS Indianapolis: Men of Courage",
    "Ustica: The Missing Paper",
    "V for Vendetta",
    "Vacation",
    "Valentine",
    "Valentine's Day",
    "Valerian and the City of a Thousand Planets",
    "Valkyrie",
    "Van Helsing",
    "Van Wilder: Freshman Year",
    "Vanilla Sky",
    "Vehicle 19",
    "Velvet Buzzsaw",
    "Venom",
    "Vera",
    "Vertical Limit",
    "Vertigo",
    "Vice",
    "Viimased",
    "Vivarium",
    "Voice from the Stone",
    "Volcano",
    "Vox Lux",
    "Waiting...",
    "Walk Hard: The Dewey Cox Story",
    "Walk the Line",
    "Walking Dead - Tomate",
    "WALL·E",
    "Wallace & Gromit: The Curse of the Were-Rabbit",
    "Wanted",
    "War",
    "War Dogs",
    "War for the Planet of the Apes",
    "War Horse",
    "War of the Worlds",
    "Warcraft",
    "WarGames",
    "Warrior",
    "Watchmen",
    "Waterworld",
    "We Are Your Friends",
    "We Summon the Darkness",
    "We're the Millers",
    "Wedding Crashers",
    "Welcome Home Roscoe Jenkins",
    "Westworld",
    "What Happened to Monday",
    "What Men Want",
    "What to Expect When You're Expecting",
    "What We Do in the Shadows",
    "What Women Want",
    "What's Eating Gilbert Grape",
    "Whiplash",
    "Who Am I - Kein System ist sicher",
    "Who Framed Roger Rabbit",
    "Why Him?",
    "Widows",
    "Wild Card",
    "Wild Child",
    "Wild Hogs",
    "Wild Rose",
    "Wild Things",
    "Wild Wild West",
    "Wildling",
    "Willy Wonka & the Chocolate Factory",
    "Winchester",
    "Wind River",
    "Winnie the Pooh",
    "Wish Upon",
    "Wishmaster",
    "Within",
    "Wizards of Waverly Place: The Movie",
    "Wolf",
    "Won't You Be My Neighbor?",
    "Wonder",
    "Wonder Park",
    "Wonder Woman",
    "Wonder Woman 1984",
    "World War Z",
    "Wrath of the Titans",
    "Wreck-It Ralph",
    "Wrong Turn",
    "Wrong Turn 2: Dead End",
    "Wrong Turn 3: Left for Dead",
    "Wrong Turn 4: Bloody Beginnings",
    "Wrong Turn 5: Bloodlines",
    "X-Men: Apocalypse",
    "X-Men: Days of Future Past",
    "X-Men: Production Scrapbook",
    "X-Rated: The Greatest Adult Movies of All Time",
    "xXx: Return of Xander Cage",
    "xXx: State of the Union",
    "Y tu mamá también",
    "Yes Man",
    "Yesterday",
    "Yoga Hosers",
    "Yogi Bear",
    "You Don't Mess with the Zohan",
    "You Got Served",
    "You Only Live Twice",
    "You Were Never Really Here",
    "You're Not Alone",
    "You've Got Mail",
    "Zack and Miri Make a Porno",
    "Zathura: A Space Adventure",
    "Zero Dark Thirty",
    "Zodiac",
    "Zombieland",
    "Zombieland: Double Tap",
    "Zoolander",
    "Zoolander 2",
    "Zoom",
    "Zootopia",
];

// ALL EVENT LISTENERS--------------------------------------------------------------------------
searchDropdown.addEventListener("keyup", filterSearch);
movies.addEventListener("click", movieSelected);

function filterSearch(e) {
    let filter, li, i;
    filter = searchMovies.value.toUpperCase();
    li = searchDropdown.getElementsByTagName("li");
    for (i = 0; i < li.length; i++) {
        txtValue = li[i].textContent || li[i].innerText;
        if (txtValue.toUpperCase().indexOf(filter) > -1) {
            li[i].style.display = "";
        } else {
            li[i].style.display = "none";
        }
    }
}
let movieName = "";

function movieSelected(e) {
    searchMovies.value = "";
    instuct.textContent = `Movies and Drinks Based on ${e.target.textContent}`;
    movieList.setAttribute("style", "display:none");
    movieName = e.target.textContent;

    // createPairs();

    //FETCH CALL MADE UPON EVENT BEING FIRED-------------------------------------------------------

    // switch tastedive.json to "https://cors-anywhere.herokuapp.com/https://tastedive.com/api/similar?info=1&type=movie&limit=4&q=movie:${movieName}&k=361760-Flixmix-JVYDSEIN"
    tstDive
        .get(
            `https://cors-anywhere.herokuapp.com/https://tastedive.com/api/similar?info=1&type=movie&limit=4&q=movie:${movieName}&k=361760-Flixmix-JVYDSEIN`
        )
        .then((data) => {
            let movies = data;

            // data.forEach((movies) => {
            //     wiki.get(movies);
            // });

            let movieInfo = wiki.get(movies).then((res) => {
                let movieArray = res;

                let movieCards = createMovieCard(movieArray);

                moviesContainer.innerHTML = movieCards;
            });
            let drinkInfo = cocktails.get().then((res) => {
                let drinkArray = res;
                let drinkCards = createDrinkCard(drinkArray);
                console.log(drinkArray);
                drinksContainer.innerHTML = drinkCards;
            });
        });
}

searchMovies.addEventListener("keyup", (e) => {
    // get input text
    if (e.target.value.length >= 3) {
        movieList.setAttribute("id", "movie-api");

        movieList.setAttribute("style", "display:");
    } else {
        movieList.setAttribute("id", "");
    }
});

searchMovies.addEventListener("keydown", (e) => {
    if (e.target.value.length <= 3) {
        movieList.setAttribute("style", "display:none");
    }
});

movieoptions.forEach(function (item) {
    let options = document.createElement("li");
    options.className = "movie-options";
    options.innerText = item;

    movieList.appendChild(options);
});

//TESSSSSSTTTTTTTT
function creatCards() {
    for (i = 0; i < 4; i++) {
        console.log(tasteDive[i].Name);
        console.log(wikiVal[i].Link);
        movieCard += ` <div class="content-movie">
<div class="card-movie">
<img
class="content-image"
id="movie-image"
alt="Picture of movie poster"
src="${wikiVal[i].Link}"
/>
<div class="movie-detail-container">
<h3 class="detail-title">
${tasteDive[i].Name}
</h3>

<p
id="card-movie-desc"
class="card-desc"
>
${tasteDive[i].wTeaser}
</p>
<button class="read-more">
READ MORE
</button>
</div>
</div>
</div>`;
    }
}

//CREATE CARD FUNCTIONS----------------------------------------------------------------------------
//CREATE MOVIE CARDS
function createMovieCard(movieArray) {
    let movies = movieArray;
    let movieCard = [];
    for (let i = 0; i < 4; i++) {
        movieCard.push(` <div class="content-movie" id='content-movie'>
    <div class="card-movie">
        <img
            class="content-image"
            id="movie-image"
            alt="Picture of movie poster"
            src="${movies[i].imgUrl}"
        />
        <div class="movie-detail-container">
            <h3 class="detail-title">
            ${movies[i].name}
            </h3>

            <p
                id="card-movie-desc"
                class="card-desc"
            >
            ${movies[i].detail}
            </p>
            <a class="read-more" href="${movies[i].trailer}" target="_blank" rel="noreferrer noopener">
               View Trailer
            </a>
        </div>
    </div>
    </div>`);
    }

    return movieCard.join(" ");
}

//CREATE DRINK CARDS

function createDrinkCard(drinkArray) {
    let drinks = drinkArray;
    let drinkCard = [];
    for (let i = 0; i < 4; i++) {
        drinkCard.push(` <div class="content-drink" id="content-drink">
<div class="card-drink">
    <img
        class="content-image"
        id="drink-image"
        alt="Picture of cocktail"
        src="${drinks[i].img}"
    />

    <div class="drink-detail-container">
        <h3>${drinks[i].name}</h3>
        <ul
            id="card-drink-desc"
            class="card-desc card-drink-desc"
        >
            ${drinks[i].ingr}
        </ul>
        <a class="read-more" href="${drinks[i].detail}" target="_blank" rel="noreferrer noopener">
               Read More
            </a>
    </div>
</div>
</div>`);
    }

    return drinkCard.join(" ");
}
//CREATE MOVIE & DRINK CARD PAIR
function cardPairs(i) {
    i = i;
    let paircard = ` ${getTasteDive()}  ${createDrinkCard(i)}`;
    return paircard;
}

//ITERATE THROUGH PAIRS

// function allPairs() {
//     let results = "";
//     for (i = 0; i < movieDesc.length; i++) {
//         results += cardPairs(i);
//     }
//     return results;
// }
//APPEND CARDS TO DOM
function createPairs(movie, drink) {
    let movieCards = movie;
    let drinkCards = drink;
    let oldCont = document.getElementById("content-container");
    let newCont = document.createElement("div");
    let MainBottomCont = document.getElementById("bottom-main-container");
    newCont.className = "content-container";
    newCont.id = "content-container";

    // <div class="pairing-results-container"> removed because of cardPair creation
    newCont.innerHTML = `<div class="content-container">
    
    
        
</div> `;

    MainBottomCont.replaceChild(newCont, oldCont);
}
